"""add constraints and indexes

Revision ID: 32cd67c1b66d
Revises: 94dbd79b0f1b
Create Date: 2026-02-15 15:41:29.780287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cd67c1b66d'
down_revision: Union[str, Sequence[str], None] = '94dbd79b0f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_incident_responders_incident_id'), 'incident_responders', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_responders_user_id'), 'incident_responders', ['user_id'], unique=False)
    op.create_unique_constraint('uq_incident_user', 'incident_responders', ['incident_id', 'user_id'])
    op.create_index('idx_incident_updates_incident_occurred', 'incident_updates', ['incident_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_incident_updates_incident_id'), 'incident_updates', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_occurred_at'), 'incident_updates', ['occurred_at'], unique=False)
    op.create_check_constraint('ck_incident_responders_role', 'incident_responders', "role IN ('responder', 'observer')")
    op.create_check_constraint('ck_incident_updates_kind', 'incident_updates', "kind IN('status_change', 'note', 'severity_change', 'action', 'comms', 'metric', 'assignment')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_updates_occurred_at'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_incident_id'), table_name='incident_updates')
    op.drop_index('idx_incident_updates_incident_occurred', table_name='incident_updates')
    op.drop_constraint('uq_incident_user', 'incident_responders', type_='unique')
    op.drop_index(op.f('ix_incident_responders_user_id'), table_name='incident_responders')
    op.drop_index(op.f('ix_incident_responders_incident_id'), table_name='incident_responders')
    op.drop_constraint("ck_incident_responders_role", "incident_responders", type_="check")
    op.drop_constraint("ck_incident_updates_kind", "incident_updates", type_="check")

    # ### end Alembic commands ###
